### ISSUE TITLE
Michael says wot?

### ISSUE THREAD

**Issue by brewermr** [CaverBruce/NP-plus-plus-CaveUDL#1]
wot?

**Comment by CaverBruce** [comment]
You know very well wot!

**Comment by brewermr** [comment]
all very interesting
thought you might be interested in this graph showing the flow of the riwaka 2 yrs ago . This is compared with our 0.6cumec yesterday. We need a drought!

Michael

**Comment by CaverBruce** [comment]
No attachment Michael?

**Comment by brewermr** [comment]
It was included in the message. pasted in . cant have been sent , damn
micahel
